import turtle as t
import turtle
window = t.getscreen()
t.pensize(55)
t.color("blue")
t.forward(70)
t.right(80)
t.circle(-90,60)
t.color("green")
t.circle(-100,85)
t.color("yellow")
t.circle(-100,95)
t.color("red")
t.circle(-100,70)
t.begin_fill()
t.hideturtle()
t.pensize(10)
t.color("red")
t.fillcolor("red")
window.mainloop()
