import turtle
turtle.title("Whatsapp logo")
windows = turtle.getscreen()
windows.bgcolor("black")
t = turtle.Turtle()
turtle.hideturtle()
t.speed(1)
t.up()
t.goto(-20, -20)
t.down()
t.color("white")
t.begin_fill()
t.circle(150)
t.end_fill()

t.up()
t.goto(-100, 10)
t.down()
t.begin_fill()
t.right(165)
t.forward(100)
t.right(130)
t.forward(100)
t.end_fill()
t.color("lime")
t.up()
t.goto(-30, -10)
t.down()
t.begin_fill()
t.right(70)
t.circle(140)
t.end_fill()
t.color("lime")
t.up()
t.goto(-100, 20)
t.down()
t.begin_fill()
t.right(160)
t.forward(80)
t.right(130)
t.forward(90)
t.end_fill()
t.color("white")
t.up()
t.goto(40, 40)
t.down()
t.begin_fill()
t.right(60)
t.circle(140,-90)
t.right(30)
t.circle(50, -50)
t.left(90)
t.forward(40)
t.right(90)
t.forward(20)
t.up()
t.goto(40, 40)
t.down()
t.right(150)
t.circle(50, 50)
t.left(80)
t.forward(40)
t.left(90)
t.forward(20)
t.left(98.5)
t.circle(95, -90)
t.end_fill()
t.color("lime")
t.width(2)
t.begin_fill()
t.circle(92, 90)
t.end_fill()
t.left(135)
t.width(5)
t.up()
t.forward(10)
t.down()
t.forward(60)
t.up()
t.goto(-150, -100)
t.down()
t.hideturtle()
windows.mainloop()
